
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class HesapMakinesi extends javax.swing.JFrame {

    /**
     * Creates new form HesapMakinesi
     */
    Scanner scanner = new Scanner(System.in);
    
    public HesapMakinesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toplama_butonu = new javax.swing.JButton();
        cikarma_butonu = new javax.swing.JButton();
        carpma_butonu = new javax.swing.JButton();
        bolme_butonu = new javax.swing.JButton();
        sonuc_yazisi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sayi1 = new javax.swing.JTextField();
        sayi2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toplama_butonu.setText("Toplama");
        toplama_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplama_butonuActionPerformed(evt);
            }
        });

        cikarma_butonu.setText("Çıkarma");
        cikarma_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarma_butonuActionPerformed(evt);
            }
        });

        carpma_butonu.setText("Çarpma");
        carpma_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carpma_butonuActionPerformed(evt);
            }
        });

        bolme_butonu.setText("Bölme");
        bolme_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolme_butonuActionPerformed(evt);
            }
        });

        jLabel1.setText("Sayi 1:");

        jLabel2.setText("Sayi 2:");

        jLabel3.setText("Sonuç :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sonuc_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(toplama_butonu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cikarma_butonu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(carpma_butonu)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bolme_butonu)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sayi2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(sayi1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(sayi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sayi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sonuc_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toplama_butonu)
                    .addComponent(cikarma_butonu)
                    .addComponent(carpma_butonu)
                    .addComponent(bolme_butonu))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toplama_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplama_butonuActionPerformed
        int birinci_sayi = Integer.valueOf(this.sayi1.getText());
        int ikinci_sayi = Integer.valueOf(this.sayi2.getText());
        
        sonuc_yazisi.setText(String.valueOf(birinci_sayi+ikinci_sayi));
    }//GEN-LAST:event_toplama_butonuActionPerformed

    private void cikarma_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarma_butonuActionPerformed
        int birinci_sayi = Integer.valueOf(this.sayi1.getText());
        int ikinci_sayi = Integer.valueOf(this.sayi2.getText());
        sonuc_yazisi.setText(String.valueOf(birinci_sayi-ikinci_sayi));
    }//GEN-LAST:event_cikarma_butonuActionPerformed

    private void carpma_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carpma_butonuActionPerformed
        int birinci_sayi = Integer.valueOf(this.sayi1.getText());
        int ikinci_sayi = Integer.valueOf(this.sayi2.getText());
        sonuc_yazisi.setText(String.valueOf(birinci_sayi*ikinci_sayi));
    }//GEN-LAST:event_carpma_butonuActionPerformed

    private void bolme_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolme_butonuActionPerformed
        int birinci_sayi = Integer.valueOf(this.sayi1.getText());
        int ikinci_sayi = Integer.valueOf(this.sayi2.getText());
        sonuc_yazisi.setText(String.valueOf((double)birinci_sayi/ikinci_sayi));
    }//GEN-LAST:event_bolme_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapMakinesi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bolme_butonu;
    private javax.swing.JButton carpma_butonu;
    private javax.swing.JButton cikarma_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField sayi1;
    private javax.swing.JTextField sayi2;
    private javax.swing.JLabel sonuc_yazisi;
    private javax.swing.JButton toplama_butonu;
    // End of variables declaration//GEN-END:variables
}
